### ISSUE TITLE
이 플러그인은 무었을 하는 플러그인입니까?

### ISSUE THREAD

**Issue by Apple6050** [parangee/projectile-skills#2]

**Comment by Apple6050** [comment]
이 플러그인은 어떤 플러그인인가요?

**Comment by parangee** [comment]
아 이거는 눈덩이 터지는거에요

**Comment by parangee** [comment]
눈덩이가 블럭에 맞으면 터져요

**Comment by Apple6050** [comment]
파랑이님 저 유튜브 닉네임 장준호에요

**Comment by Apple6050** [comment]
이 플러그인에 필요한 다른 플러그인은 없습니까?
그리고 버전은요?
버킷 종류도 알려주세요

**Comment by parangee** [comment]
이 플러그인은 [Kotlin Plugin](https://github.com/noonmaru/kotlin-plugin) 적용해주시고

버전은 1.15.2입니다.

페이퍼 플러그인으로 만들었습니다.

플러그인 파일은 릴리즈에 있어요.

**Comment by Apple6050** [comment]
네
